apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hsk-etymology-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - haquocbao.id.vn
    secretName: hsk-etymology-tls
  rules:
  - host: haquocbao.id.vn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hsk-etymology-service
            port:
              number: 80
